### ISSUE TITLE
Is this extension now obsolete, since Nova now fully supports .editorconfig?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [jsmecham/nova-whitespace#9]
Hi there!

I was using your extension since the early days of the Nova beta because I found it so useful...

But since Nova now fully supports all `.editorconfig` options, I wonder if your extension is still necessary? Does it do anything else besides trimming trailing whitespace? Granted, it also trims trailing whitespace _without_ `.editorconfig` being present, but is the extra overhead of Yet Another Extension worth it, when all it takes to get automatic whitespace trimming is having few bytes on an extra file?

I'm just curious what you have in mind with this extension and what you intend to use it for in the future.

Thanks in advance for your insights!

**Comment by ConnectGrid** [comment]
I wasn't aware that `.editorconfig` offered a whitespace-trimming option. I'll have to look into that, as you're right... it would make it a "native" feature of Nova in a sense.

`trim_trailing_whitespace`

(Note, I emailed the author last week and he responded saying that he'll push out an update very soon that hopefully addresses any outstanding issues.)

**Comment by ConnectGrid** [comment]
I just tested the `.editorconfig` whitespace trimming and it works great without a delay.

But Nova does seem to be confused about the cursor position. It moves the cursor to a position relative to where it was. If 4 spaces are trimmed, it moves the cursor 4 positions forward, which is a strange behaviour. I'll report that to Nova directly.

To the author of this plugin... can it — disable itself if `.editorconfig` is already trimming whitespace, so this extension only becomes a fallback?

**Comment by GwynethLlewelyn** [comment]
@ConnectGrid, sounds like a plan! 😸 

I haven't experienced the cursor position issue you describe, but I guess I'll have to do more checks... maybe I wasn't even _aware_ of that issue...
